### PR TITLE
Add current agreed license language.

### PR DESCRIPTION
**Pull request by asakatida**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description

This is pending consensus on #11. I can update the file list if other PRs get merged in the mean time.

### CODE REVIEW

**Comment by floydkots** [comment]
Great! Thank you @grandquista.

**Comment by floydkots** [comment]
I propose we consider issue #11 as resolved. Should any dissatisfaction be registered thereafter, we can always reopen the issue.

If we agree with this, then we could review and merge this PR (#16) so I can pull the changes from my end, and complete the fixes of issues #8, #14 and #17.

**Comment by gabor-boros** [comment]
@floydkots, can we merge this PR?

**Comment by floydkots** [comment]
Sure. Merging it.

**Pull request merged**
