### PR TITLE
Purge V8, admin and driver dependencies, files and references.

### PR DESCRIPTION
**Pull request by floydkots**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description
Purged the remaining dependencies, files and references to V8, the admin dashboard and drivers.
V8 was replaced with Duktape, the embeddable JavaScript engine while the admin and driver folders were removed and made independent repositories.

Also ignored .log files.

### CODE REVIEW

**Comment by thelinuxlich** [comment]
Thanks!

**Comment by thelinuxlich** [comment]
Can you also remove Windows support?

**Comment by floydkots** [comment]
Sure... I'll look into it. It's just a bit more involved, so, it'll take quite some time.

**Comment by atris** [comment]
Will review this over this weekend.

**Comment by floydkots** [comment]
:+1:

**Review by asakatida — APPROVED** [review]
Everything checks out on my review. I feel like looking at the diff there is some more dead code, but that can be cleaned out when I have time.

**Comment by thelinuxlich** [comment]
So maybe merge this and remove the windows artifacts in a new PR

**Comment by atris** [comment]
Merged, thanks!

**Pull request merged**
