### PR TITLE
Making changes from next branch to 2.4 release branch

### PR DESCRIPTION
**Pull request by atris**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description
Making changes from next branch to 2.4 release branch

### CODE REVIEW

**Comment by atris** [comment]
@thelinuxlich @grandquista Please take a look and let me know if it seems ok. It should be fine, but I want to be extremely sure. Post the merge, I will cut a release

**Comment by asakatida** [comment]
This all looks good. I can look into your comment on test cases for in process execution on Monday if that should be covered before releasing.

**Comment by thelinuxlich** [comment]
It's awesome we are reaching release!

**Comment by atris** [comment]
@grandquistaea Please do. I will not block the release on it though. Please do it and we can do a hot fix if needed

**Pull request merged**
