### PR TITLE
added rethinkdbdash driver

### PR DESCRIPTION
**Pull request by dunklesToast**
- [ x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description
- added rethinkdbdash driver

### CODE REVIEW

**Comment by thelinuxlich** [comment]
Hi dunkles, we will have to create a totally new README.md because of the fork and new drivers under our organization.

**Comment by atris** [comment]
I believe that we should have a fork of the driver in the repository and not directly use RethinkDB's drivers.

**Comment by thelinuxlich** [comment]
We have a fork in our organization

**Comment by atris** [comment]
Ah, ok. I commented since the PR points to the old driver. We should abandon this PR then

**Pull request closed without merging**
