### PR TITLE
Minor integration cleanups

### PR DESCRIPTION
**Pull request by asakatida**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description
Minor pieces to assist in debugging this script.

### CODE REVIEW

**Review by gabor-boros — APPROVED** [review]
Nice improvements!

**Comment by gabor-boros** [comment]
Codacy adjusted. The check did not refreshed, but no pending issues remained so merging the PR.

Update I cannot merge.

**Comment by asakatida** [comment]
@gabor-boros fixed your permissions.

**Comment by gabor-boros** [comment]
Restarted the codacy check

**Pull request merged**
