### PR TITLE
Updating documentation links of drivers.

### PR DESCRIPTION
**Pull request by talut**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description
Updating documentation links of drivers. Some of them redirection to correct repo but like rebirthdb-go is not redirection to anywhere so Github is saying Page Not Found.

### CODE REVIEW

**Comment by talut** [comment]
Is it necessary to change the name of the drivers? Like, rebirthdb-elixir to rethinkdb-elixir. I would like to change if necessary.

**Comment by atris** [comment]
Can you check why Shippable run is failing?

**Comment by atris** [comment]
> Is it necessary to change the name of the drivers? Like, rebirthdb-elixir to rethinkdb-elixir. I would like to change if necessary.

Yes, we are merged as RethinkDB, so the drivers are official RethinkDB drivers now. So renaming is necessary

**Comment by talut** [comment]
@atris I clicking details is saying page not found. I'm only updated README.md for links nothing else. 
Also I will renaming now 👍

**Comment by talut** [comment]
@atris I just now renamed drivers. Also I just started to using rethinkDB and I'll be very happy if I can help with anything else.

Note : I just see the shippable failed reason : 

`runs|_cleanRunYml|callerId:5b7af77d6441ff06008edab8|projectId:5b7afe4ef50d42070021579f|_cleanLanguage Invalid RUN language: cpp`

**Pull request merged**
